### ISSUE TITLE
Not running on linux

### ISSUE THREAD

**Issue by abdushakoor12** [danReynolds/loon#15]
![image](https://github.com/user-attachments/assets/62419e6b-9e8a-4872-9633-4b7d6b70231c)

**Comment by abdushakoor12** [comment]
Looks like linux needs to have some things installed for flutter_secure_storage

https://stackoverflow.com/a/69089348/12289192

So this is more of a flutter_secure_storage and linux thing and this issue can be closed.

Maybe, we could add instructions in Readme for linux users

**Comment by danReynolds** [comment]
Ah yea that's interesting! I've never run it on Linux. I'll add some instructions somewhere

**Comment by abdushakoor12** [comment]
flutter_secure_storage is also causing the following issue on macos

Error log:

```shell
Connecting to VM Service at ws://127.0.0.1:53753/yY24VLuod8Y=/ws
Connected to the VM Service.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Unexpected security result code, Code: -34018, Message: A required entitlement isn't present., -34018, null)

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_sendPort@322361354' has not been initialized.
#0      FilePersistor._sendPort (package:loon/persistor/file_persistor/file_persistor.dart)
#1      FilePersistor._sendMessage (package:loon/persistor/file_persistor/file_persistor.dart:90:5)
file_persistor.dart:90
#2      FilePersistor.hydrate (package:loon/persistor/file_persistor/file_persistor.dart:171:28)
file_persistor.dart:171
#3      PersistManager._next (package:loon/persistor/persist_manager.dart:56:40)
persist_manager.dart:56
<asynchronous suspension>

```

**Comment by danReynolds** [comment]
Looking

**Comment by danReynolds** [comment]
I mostly build targeting iOS and Android but on MacOS I had to make sure that the keysharing entitlement was signed for my debug build: https://github.com/mogol/flutter_secure_storage/issues/350#issuecomment-1097123273

Have you done that step?

**Comment by danReynolds** [comment]
if that ends up being your issue I've got a PR here to call it out: https://github.com/danReynolds/loon/pull/16

**Comment by abdushakoor12** [comment]
@danReynolds I'll try that. Thanks.

**Comment by abdushakoor12** [comment]
> if that ends up being your issue I've got a PR here to call it out: https://github.com/danReynolds/loon/pull/16

I tried bumping flutter_secure_storage in my fork and using that, but it didn't solve the issue. Maybe Xcode will.

**Comment by danReynolds** [comment]
> > if that ends up being your issue I've got a PR here to call it out: https://github.com/danReynolds/loon/pull/16
> 
> I tried bumping flutter_secure_storage in my fork and using that, but it didn't solve the issue. Maybe Xcode will. 
> 
> 

Yea I had to add the capability in XCode and update my signing of the debug build and that did it

You'll want to blow away your persistence file too if you have stale corrupted data in your documents/loon folder
